name: CI-CD WordPress

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Kompose
        run: |
          curl -L https://github.com/kubernetes/kompose/releases/download/v1.32.0/kompose-linux-amd64 -o kompose
          chmod +x kompose
          sudo mv kompose /usr/local/bin/kompose

      - name: Generate Kubernetes manifests with Kompose
        run: |
          rm -rf kube
          mkdir kube
          kompose convert -o kube/

      - name: Add Kubernetes Secret
        run: |
          cp kube/wordpress-secret.yaml kube/wordpress-secret.yaml || true

      - name: Zip Kubernetes manifests
        run: |
          zip -r CabanelLucienWordpress.zip kube

      - name: Upload ZIP to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.cluster114.hosting.ovh.net
          username: ludivinej
          password: Passtemp26
          server-dir: RenduDevopsKube/
          local-dir: ./
